views/blog/__init__.py
from datetime import datetime

from flask import render_template, Blueprint, url_for, request
from flask_login import login_required, current_user

from helpers import DBConnection
from models import Post
from markdownify import markdownify as md


blog = Blueprint("Blog", __name__)


@blog.route("/blog/")
@blog.route("/blog")
def home():
    with DBConnection() as db:
        blog_posts = db.session.query(Post).all()

    print(url_for("Blog.blog_post", title="Test"))
    return render_template(
        "blog/blog_home.html",
        blog_posts=blog_posts
    )


@blog.route("/blog/<title>/")
@blog.route("/blog/<title>")
def blog_post(title):

    with DBConnection() as db:
        post = db.session.query(Post).filter(
            Post.title == title
        ).first()

    return render_template(
        "blog/blog.html",
        post=post
    )


@blog.route("/blog/<title>/edit/")
@blog.route("/blog/<title>/edit")
@login_required
def blog_edit(title):

    with DBConnection() as db:
        post = db.session.query(Post).filter(
            Post.title == title
        ).first()

    return render_template(
        "blog/blog_editor.html",
        post=post
    )


@blog.route("/blog/save/", methods=["POST"])
@blog.route("/blog/save", methods=["POST"])
def blog_save():
    data = request.form
    title = "Blog post"
    content = ""

    # It's easier to ask for forgiveness than permission, check if we can look up the post, otherwise fail to None
    # noinspection PyBroadException
    try:
        with DBConnection() as db:
            existing_post = db.session.query(Post).filter(Post.post_id == data["post_id"]).first()
    except:
        existing_post = None

    if "title" in data.keys():
        # remove the nonsense from the title
        title = data["title"]
        title = title.replace("<p>", "").replace("</p>", "")
        title = title.replace("<h1>", "").replace("</h1>", "")
        title = title.replace("\n", "").replace("\r", "").replace("  ", "")

    if "content" in data.keys():
        content = md(data["content"])

    with DBConnection() as db:
        if not existing_post:
            post = Post(title, content, user_id=current_user.user_id)
            db.session.add(post)
            db.session.commit()
        else:
            if title != "" and title != existing_post.title:
                existing_post.title = title

            existing_post.content = content
            if existing_post.created_timestamp is None:
                existing_post.created_timestamp = datetime.now()

            existing_post.updated_timestamp = datetime.now()

            # add it back to the db
            db.session.add(existing_post)
            db.session.commit()
            # set title, not sure this is necessary...
            title = existing_post.title

    return url_for("Blog.blog_post", title=title)


@blog.route("/blog/new/")
@blog.route("/blog/new")
@login_required
def blog_new():
    return render_template(
        "blog/blog_editor.html",
    )

templates/blog/blog.html
{% extends "blog/blog_master.html" %}

{% block content %}
<section id="post">
  <div class=" col-lg-8 col-md-8 col-sm-8 col-xs-12" style="float:none; margin: 0px auto;">
    <h1 class="blog-title">{{ post.title }}</h1>
    <p class="blog-description">
      Posted by {{ post.user }} on {{ post.friendly_timestamp }}
    </p>
    <div>
      {{ post.html_content }}
    </div>
    <hr>

    <div style="padding-bottom: 30px;">
      {% if current_user.is_admin %}
      <a class="btn btn-primary" href="{{ url_for("Blog.blog_edit", title=post.title) }}">Edit</a>
      {% endif %}
    </div>
    <div>
        <a class="btn btn-primary" href="{{ url_for("Blog.home") }}">Return to blog list</a>
    </div>
  </div>

</section>
{% endblock %}

templates/blog/blog_editor.html
{% extends "blog/blog_master.html" %}

{% block content %}
<section id="post">
  <div class=" col-lg-8 col-md-8 col-sm-8 col-xs-12" style="float:none; margin: 0px auto;">
    <form>
      <div data-editable data-name="title" class="title">
        <h1>
          {% if post %}
          {{ post.title }}
          {% else %}
          Blog title
          {% endif %}
        </h1>
      </div>
      <div>
        <div data-editable data-name="content" class="content">
          <p>
            {% if post %}
            {{ post.html_content }}
            {% else %}
            Content should go here
            {% endif %}
          </p>
        </div>
      </div>
      <hr>
      <div>
        <a class="btn btn-primary" href="{{ url_for("Blog.home") }}">Return to blog list</a>
      </div>
    </form>
  </div>

</section>
{% endblock %}

{% block styles %}
  <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="bower_components/ContentTools/build/content-tools.min.css") }}">

  <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="css/editor.css") }}">
{% endblock %}

{% block scripts %}
  <script src="{{ url_for("static", filename="bower_components/ContentTools/build/content-tools.min.js") }}"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

  <script>
    window.addEventListener('load', function(){
    // initialize the editor
    var editor = ContentTools.EditorApp.get();
    editor.init('*[data-editable]', 'data-name');

    editor.addEventListener('saved', function(event){
      // Check that something changed

      var regions = editor.regions();

      if(Object.keys(regions).length === 0){
        return;
      }

      {% if post %}
      var post_id = {{ post.post_id }};
      {% else %}
        var post_id = null;
      {% endif %}

      // Set the editor as busy while we save our changes
      this.busy(true);

      // Collect the contents of each region into a FormData instance
      var data = new FormData();
      for(var name in regions){
        if(regions.hasOwnProperty(name)){
          {#console.log(name, regions[name].html());#}
          data.append(name, regions[name].html());
        }
      }
      data.append("post_id", post_id);

      {# Send the server the data #}
      axios.post("{{ url_for("Blog.blog_save") }}", data).then(function(event){
        console.log("got", event, "back from the server");
        window.location = event.data;
      }).catch(function(error){
        editor.busy(false);
        console.log(error);
        new ContentTools.FlashUI('no');
      });


    });
  });

  </script>
{% endblock %}

templates/blog/blog_home.html
{% extends "blog/blog_master.html" %}

{% block content %}
<section id="posts">
  <div class="blog-header">
    <div class="container">
      <h1 class="blog-title">{{ blog_title }}</h1>
      <p class="lead blog-description">{{ blog_description }}</p>
    </div>
  </div>
  <div class=" col-lg-8 col-md-8 col-sm-8 col-xs-12" style="float:none; margin: 0px auto;">
  {% for blog in blog_posts %}
    <div class="blog-post" >
      <h2 class="blog-post-title">
        <a href="{{ url_for("Blog.blog_post", title=blog.title) }}">{{ blog.title }}</a>
      </h2>
      <p class="blog-post-meta">Posted by {{ blog.user }} on {{ blog.friendly_timestamp }}</p>
      <p>{{ blog.summary }}...<a href="{{ url_for("Blog.blog_post", title=blog.title) }}"> Continue reading</a></p>
      <hr>
    </div>
  {% else %}
   <div class="card border-mint rounded my-5 bg-transparent  col-lg-8 col-md-8 col-sm-6 col-xs-12" style="float:none; margin: 0px auto;">
      <div class="card-header bg-transparent text-center text-primary card-title"></div>
      <div class="card-body text-dark">
        <p class="card-text">No entries to display</p>
      </div>
    </div>
  {% endfor %}
    <div>
    {% if current_user.is_admin %}
    <a class="btn btn-primary" href="{{ url_for("Blog.blog_new") }}">New post</a>
    {% endif %}
    </div>
  </div>
</section>
{% endblock %}

templates/blog/blog_master.html
{% extends "master.html" %}