views/__init__.py
from datetime import datetime

import flask
from flask import render_template, Blueprint, request, url_for, redirect
from flask_admin.helpers import is_safe_url
from flask_login import logout_user, current_user, login_user

from forms import LoginForm
from helpers import DBConnection
from helpers.security import password_hash
from models import User
from .blog import blog
from .data import data
from .event import event

main = Blueprint("Main", __name__)


@main.route('/')
def home():
    return render_template('home.html')


@main.route('/login', methods=["GET", "POST"])
def login():
    if current_user is not None and current_user.is_authenticated:
        return redirect(url_for("Main.home"))

    # create an instance of the LoginForm
    login_form = LoginForm()

    if login_form.validate_on_submit():
        username = login_form.data["username"]
        password = login_form.data["password"]

        auth = False
        logged_in = False

        with DBConnection() as db:
            user = db.session.query(User).filter(User.username == username).first()

        if user and user.password == password_hash(password, user.password_salt):
            auth = True

        if auth:
            try:
                logged_in = login_user(user)
            except:
                # don't really care if errors happen here
                pass

        if logged_in:
            user.authenticated = True
            user.last_login = datetime.now()
            with DBConnection() as db:
                db.session.add(user)
                db.session.commit()
                db.session.close()

            next_url = request.args.get("next")

            if next_url is None or not is_safe_url(next_url):
                return redirect(url_for("Main.home"))
            else:
                return redirect(next_url or url_for("Main.home"))

    return render_template(
        "login.html",
        login_form=login_form
    )


@main.route('/logout')
def logout():
    user = current_user
    if user.is_authenticated:
        logout_user()
    return redirect(url_for("Main.home"))

views/blog/__init__.py
from datetime import datetime

from flask import render_template, Blueprint, url_for, request
from flask_login import login_required, current_user

from helpers import DBConnection
from models import Post
from markdownify import markdownify as md


blog = Blueprint("Blog", __name__)


@blog.route("/blog/")
@blog.route("/blog")
def home():
    with DBConnection() as db:
        blog_posts = db.session.query(Post).all()

    print(url_for("Blog.blog_post", title="Test"))
    return render_template(
        "blog/blog_home.html",
        blog_posts=blog_posts
    )


@blog.route("/blog/<title>/")
@blog.route("/blog/<title>")
def blog_post(title):

    with DBConnection() as db:
        post = db.session.query(Post).filter(
            Post.title == title
        ).first()

    return render_template(
        "blog/blog.html",
        post=post
    )


@blog.route("/blog/<title>/edit/")
@blog.route("/blog/<title>/edit")
@login_required
def blog_edit(title):

    with DBConnection() as db:
        post = db.session.query(Post).filter(
            Post.title == title
        ).first()

    return render_template(
        "blog/blog_editor.html",
        post=post
    )


@blog.route("/blog/save/", methods=["POST"])
@blog.route("/blog/save", methods=["POST"])
def blog_save():
    data = request.form
    title = "Blog post"
    content = ""

    # It's easier to ask for forgiveness than permission, check if we can look up the post, otherwise fail to None
    # noinspection PyBroadException
    try:
        with DBConnection() as db:
            existing_post = db.session.query(Post).filter(Post.post_id == data["post_id"]).first()
    except:
        existing_post = None

    if "title" in data.keys():
        # remove the nonsense from the title
        title = data["title"]
        title = title.replace("<p>", "").replace("</p>", "")
        title = title.replace("<h1>", "").replace("</h1>", "")
        title = title.replace("\n", "").replace("\r", "").replace("  ", "")

    if "content" in data.keys():
        content = md(data["content"])

    with DBConnection() as db:
        if not existing_post:
            post = Post(title, content, user_id=current_user.user_id)
            db.session.add(post)
            db.session.commit()
        else:
            if title != "" and title != existing_post.title:
                existing_post.title = title

            existing_post.content = content
            if existing_post.created_timestamp is None:
                existing_post.created_timestamp = datetime.now()

            existing_post.updated_timestamp = datetime.now()

            # add it back to the db
            db.session.add(existing_post)
            db.session.commit()
            # set title, not sure this is necessary...
            title = existing_post.title

    return url_for("Blog.blog_post", title=title)


@blog.route("/blog/new/")
@blog.route("/blog/new")
@login_required
def blog_new():
    return render_template(
        "blog/blog_editor.html",
    )

views/data/__init__.py
from flask import Blueprint, jsonify

from helpers import Calendar, DBConnection
from models import Post, Event

data = Blueprint("Data", __name__)


@data.route('/data/events/<int:max_events>')
@data.route('/data/events', defaults={'max_events': 10})
def event_data(max_events: int):
    calendar = Calendar()

    with DBConnection() as db:
        events = calendar.get_json_events(db, max_events)

    return jsonify(events)


@data.route('/data/blogs/<int:limit>')
@data.route('/data/blogs', defaults={'limit': 100})
def blogs_data(limit: int):
    with DBConnection() as db:
        posts = db.session.query(Post).limit(limit).all()

    return jsonify(posts)

templates/about.html
{% extends "master.html" %}

{% block content %}

{% endblock %}

templates/home.html
{% extends "master.html" %}

{% block content %}
<div id="hero">
  <div style="padding: 35vh 0; color: #FFF;" class="text-center">
    <h1 id="logo">PHORGE</h1>
    <h3 id="tagline">Makerspace</h3>
    <a class="downArrow bounce" href="#who"><img id="arrow" src="/static/img/arrow.png"></a>
  </div>
</div>
<div id="who" class="container">
  <div class="row">
    <div class="info col-sm-12 col-md-4 text-center">
      <h1 class="title">Who are we?</h1>
      <p>
        Phorge Makerspace is a community of makers with roots extending throughout Wyoming. Join us to
        share, create, collaborate, research, develop, mentor, cross-pollinate, play, and of course...learn!
      </p>
    </div>
    <div class="info col-sm-12 col-md-8 text-center">
      <h1 class="title">What is a Makerspace?</h1>
      <blockquote>
        <p>
          A makerspace is a place in which people with shared interests can gather to work on projects while sharing
          ideas, equipment, and knowledge. A makerspace's interests can be truly diverse - including
          sewing, rocketry, fabrication, 3d printing, coding, woodworking, soap-making, and more. These
          spaces are also help to prepare those who need the critical 21st century skills in the fields
          of science, technology, engineering and math (STEM).
        </p>
      </blockquote>
    </div>
  </div>
  <div class="row">
    <div class="info col-12 text-center">
      <h1>Want to know more?</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-4 text-center">
      <img class="company-img" src="/static/img/facebook.png">
      <h6 style="margin-bottom: 2.2vw;">Have a Facebook page? Come see what we're about and check out our upcoming events.</h6>
      <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fphorgemakerspace&tabs=timeline%2C%20messages&width=330&height=270&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=false&appId" width="330" height="270" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
    </div>
    <div class="col-sm-12 col-md-4 text-center">
      <img class="company-img" src="/static/img/slack.png">
      <h6>Many of us communicate on Slack. Join us to talk about what you're interested in.</h6>
      <br>
      <iframe id="slackin" src="https://phorge-slack.herokuapp.com/iframe/dialog" style="width: 250px; height: 270px; border-width: 0px;"></iframe>
    </div>
    <div class="col-sm-12 col-md-4 text-center">
      <img class="company-img" src="/static/img/paypal.png">
      <!-- <h6>Become a member to show your continued support.</h6>
      <form>
        <div class="form-group">
          <label for="membership">Select your membership</label>
          <select class="form-control" id="membership" disabled>
            <option value="contributor">Contributor: $10.00/mo</option>
            <option value="student">Student Membership: $20.00/mo</option>
            <option value="full">Full Membership: $30.00/mo</option>
            <option value="family">Family Membership: $70.00/mo</option>
          </select>
          <br>
          <button class="btn btn-primary" type="button" disabled>Become a member</button>
        </div>
      </form> -->
      <h6>Interested in showing support? Please consider a one-time (or recurring) donation!</h6>
      <br>
      <br>
      <br>
      <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="YPS9D54C6BWPU">
        <button style="width: 70%;" class="btn btn-primary" type="submit">Donate with PayPal</button>
      </form>
        <br>
        <div class="form-group">
          <h6><em>OR</em></h6>
          <br>
          <button style="width: 70%; height: 40px;" data-sparky-open="#modal-spark" class="spark sb-blue sb-text-white" alt="Spark, the easy way to pay with Dash.">
            <img src="https://get-spark.com/button-generator/img/dash-white.svg"/>
            <span>Donate with Dash</span>
          </button>

          <div id="modal-spark" data-sparky-address="XhdbbVc2ke4tka1nmVcVm2cBnQMPo2PuSF"></div>
        </div>
    </div>
  </div>

  <div class="row">
    <div class="info col-12">
      <div id="mc_embed_signup">
        <form action="https://facebook.us18.list-manage.com/subscribe/post?u=e6093a1650c3f74a59bb43e2a&amp;id=2e385282cc"
          method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate"
          target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
            <h1 class="title orange">Subscribe to our newsletter</h1>
            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_e6093a1650c3f74a59bb43e2a_2e385282cc" tabindex="-1" value=""></div>
            <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
          </div>
        </form>
      </div>
    </div>
  </div>

</div>
<div id="events" class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="title">Events & Workshops</h1>
{#         <iframe src="https://feed.mikle.com/widget/v2/79374/" height="454px" width="100%" class="fw-iframe" scrolling="no" frameborder="0"></iframe>#}
      <div class="list-group-item phorge-event-list-item">
        <h5><i class="fa fa-calendar"></i>&nbsp;Upcoming Events</h5>
      </div>
      <div class="list-group phorge-event-list" id="event_list">
        <div v-for="event in events" class="list-group-item phorge-event-list-item" v-cloak="">
          <span :data-google_id="event.google_id"></span>
          <h6><a class="orange" :href="event.link" target="_blank">${ event.summary }$</a></h6>
          <div>
            <span class="col-10"><i class="fa fa-clock-o"></i>&nbsp;${ event.date }$</span>
            <span class="col-2"><a v-if="event.phorge_id > 0" class="btn btn-primary" :href="'/event/' + event.phorge_id">Register!</a></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{#<div id="projects" class="container">#}
{#  <div class="row">#}
{#    <div class="col-12">#}
{#      <h1 class="title" align="right">Projects</h1>#}
{#      <p>Put blog here....</p>#}
{#    </div>#}
{#  </div>#}
{#</div>#}
<div id="press" class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="title">Press</h1>
      <div class="row">
        {# First Article #}
        <div class="col-sm-12 col-md-4">
          <div class="card article">
            <img class="card-img-top" src="https://dallyup.co/wp-content/uploads/sites/3/2018/05/IMG_1642-960x640.jpg">
            <div class="card-body">
              <h5 class="card-title">Phorge Makerspace is Here</h5>
              <p class="card-text">Wyoming STEM Lab announced at their meeting on Monday that they...</p>
              <a href="https://dallyup.co/2018/05/16/phorge-makerspace-is-here/" target="_blank" class="btn btn-primary">Read</a>
            </div>
          </div>
        </div>
        {# Second Article #}
        <div class="col-sm-12 col-md-4">
          <div class="card article">
            <img class="card-img-top" src="http://thesheridanpress.com/wp-content/uploads/2018/05/05-16-18-Phorge-Makerspace-founders.jpg">
            <div class="card-body">
              <h5 class="card-title">Phorge aims to connect, educate</h5>
              <p class="card-text">Steve Butler and Spencer Kuzara met about three years ago through...</p>
              <a href="http://thesheridanpress.com/88467/phorge-makerspace-aims-to-connect-educate/" target="_blank" class="btn btn-primary">Read</a>
            </div>
          </div>
        </div>
        {# Third Article #}
        <div class="col-sm-12 col-md-4">
          <div class="card article">
            <img class="card-img-top" src="https://cdn1.sheridanmedia.com/files/imagecache/250px/image/08-06-18_p3.jpg">
            <div class="card-body">
              <h5 class="card-title">Phorge: A New Sheridan Non-Profit</h5>
              <p class="card-text">Recently, Sheridan County became...</p>
              <a href="https://sheridanmedia.com/news/phorge-new-sheridan-non-profit100585" target="_blank" class="btn btn-primary">Read</a>
            </div>
          </div>
        </div>
        {# End Articles #}
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block styles %}
  <link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">

  <style>
    .phorge-event-list{
      display: flex;
      flex:1;
      overflow: scroll;
      height: 450px;
      width: 100%;
    }
    .phorge-event-list-item{
      width: 100%;
    }
    [v-cloak] {
      display: none;
    }
  </style>
{% endblock %}

{% block scripts %}
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="https://get-spark.com/button-generator/js/sparky.js"></script>
  <script src="https://unpkg.com/vue"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

  <script>
  var event_list = new Vue({
  el: '#event_list',
  delimiters: ['${', '}$'],
  data: {
    events: []
  },
  beforeMount(){
    this.get_data();
  },
  methods:{
    get_data(){
      var self = this;

      axios.get("{{ url_for("Data.event_data") }}").then(
        function(response){
          self.events = response.data;
        }
      )
    }
  }

})
  </script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login V15</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{{ url_for("static", filename="img/favicon.ico") }}"/>
  <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="bower_components/bootstrap/dist/css/bootstrap.min.css") }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="bower_components/font-awesome/css/font-awesome.min.css") }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="css/style.css") }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="css/login.css") }}">


</head>
<body>
<div class="login-page">
  <div class="form">
    <h1>Login to <i class="phorge-font">PHORGE</i></h1>
    <form class="login-form" method="post">
      {{ login_form.csrf_token }}
      {{ login_form.hidden_tag() }}
      <div class="input-group">
        {{ login_form.username(placeholder="Email/username", class_="form-control") }}
      </div>
      <div class="input-group">
        {{ login_form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button class="btn btn-primary">login</button>
    </form>
  </div>
</div>

<script src="{{ url_for("static", filename="bower_components/jquery/dist/jquery.min.js") }}"></script>
<script src="{{ url_for("static", filename="bower_components/bootstrap/dist/js/bootstrap.min.js") }}"></script>

</body>
</html>

templates/master.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{{ page_title }}</title>
  {% block meta %}
    <meta name="description" content="Phorge, Inc."/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta property="og:locale" content="en_US"/>
    <meta property="og:url" content="{{ url_for("Main.home") }}"/>
    <meta property="og:type" content="website"/>
    <meta property="og:site_name" content="{{ site_name }}"/>
    <meta property="og:title" content="Makerspace in Sheridan County Wyoming"/>
  {% endblock %}

  {% block main_styles %}
    {#<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for("static", filename="img/favicon.ico") }}">#}
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/bootstrap/dist/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bower_components/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="https://get-spark.com/button-generator/css/sparky-button.min.css">
    <link rel="stylesheet" href="https://get-spark.com/button-generator/css/sparky-modal.min.css">
  {% endblock %}

  {% block styles %}
    {# template specific styles go here #}
  {% endblock %}

</head>
<body class="bg-faded">
{% block top_nav %}
  <nav id="topNav" class="navbar fixed-top navbar-expand-sm">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
        <span>☰</span>
      </button>
      <a class="navbar-brand page-scroll" href="{{ url_for("Main.home") }}">PHORGE</a>
      <div class="collapse navbar-collapse" id="collapsingNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link page-scroll" href="{{ url_for("Main.home") }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="{{ url_for("Main.home") }}#who">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="{{ url_for("Main.home") }}#events">Events & Workshops</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="{{ url_for("Blog.home") }}">Blog/Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="{{ url_for("Main.home") }}#press">Press</a>
          </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            {% if current_user.is_authenticated %}
              <a class="btn btn-primary" href="{{ url_for("admin.index") }}">Admin</a>
              <a class="btn btn-primary" href="{{ url_for("Main.logout") }}">Logout</a>
            {% else %}
              <a class="btn btn-primary" href="{{ url_for("Main.login") }}">Login</a>
            {% endif %}
          </li>

          <li class="navbar-brand">

            {#<img src="{{ url_for("static", filename="img/logo.png") }}" width="50" height="30" class="d-inline-block align-middle img-fluid" alt="">#}
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

<div>
  {% block content %}
    {# content will go here #}
  {% endblock %}
</div>

{% block footer %}
  <footer id="footer">
    <div class="container">
      <div class="row">
        <div class="col-12 column">
          <span class="float-right text-muted small">
            &copy; <script>document.write(new Date().getFullYear())</script> Phorge, Inc.
          </span>
        </div>
      </div>
    </div>
  </footer>
{% endblock %}

{% block main_scripts %}
  {# Main scripts needed for the whole site #}
  <script src="{{ url_for("static", filename="bower_components/jquery/dist/jquery.min.js") }}"></script>
  <script src="{{ url_for("static", filename="bower_components/bootstrap/dist/js/bootstrap.min.js") }}"></script>
  <script>
    $('a[href*="#"]').not('[href="#"]').click(function() {
      if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') || location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
        if (target.length) {
          $('html,body').animate({
            scrollTop: target.offset().top
          }, 1000);
        return false;
        }
      }
    });
  </script>
{% endblock %}

{% block scripts %}
  {# template specific scripts go here #}
{% endblock %}
</body>
</html>